SIS.Lab1_2/Controllers/BLObjectsController.cs
using SIS.Lab1_2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SIS.Lab1_2.Controllers
{
    public class BLObjectsController : Controller
    {
        private SisLab1DbContext db;

        public BLObjectsController()
        {
            db = new SisLab1DbContext();
        }

        private User AppUser
        {
            get
            {
                return Session["UserData"] as Models.User;
            }
        }

        // GET: BLObjects
        public ActionResult Index()
        {
            return View(db.BLObjects.ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(BLObject obj)
        {
            db.BLObjects.Add(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public ActionResult Edit(int id)
        {
            BLObject obj = db.BLObjects.FirstOrDefault(o => o.Id == id);

            return View(obj);
        }
        [HttpPost]
        public ActionResult Edit(BLObject obj)
        {
            db.BLObjects.Attach(obj);
            db.Entry(obj).State = System.Data.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            BLObject objToDelete = db.BLObjects.Find(id);
            return View(objToDelete);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            BLObject obj = db.BLObjects.Find(id);
            db.BLObjects.Remove(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Write(int id)
        {
            BLObject obj = db.BLObjects.FirstOrDefault(o => o.Id == id);
            if (obj.SecurityLevel < AppUser.SecurityLevel && !AppUser.IsInRole("admin"))
            {
                return RedirectToAction("Index");
            }
            return View("Edit", obj);
        }
        [HttpPost]
        public ActionResult Write(BLObject obj)
        {
            db.BLObjects.Attach(obj);
            db.Entry(obj).State = System.Data.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Read(int id)
        {
            BLObject obj = db.BLObjects.FirstOrDefault(o => o.Id == id);
            if (obj.SecurityLevel > AppUser.SecurityLevel && !AppUser.IsInRole("admin"))
            {
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

SIS.Lab1_2/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SIS.Lab1_2.Models;
using System.Security.Cryptography;

namespace SIS.Lab1_2.Controllers
{
    public class UsersController : Controller
    {
        private SisLab1DbContext db = new SisLab1DbContext();

        private Models.User AppUser
        {
            get
            {
                return Session["UserData"] as Models.User;
            }
        }

        // GET: Users
        public ActionResult Index()
        {
            if (AppUser == null)
            {
                return RedirectToAction("Login", "Account");
            }
            if (AppUser.IsInRole("Admin"))
            {
                return View(db.Users.ToList());
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (AppUser.Roles.First(r => r.Id == 1) != null && AppUser != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                User user = db.Users.Find(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                return View(user);
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            if (AppUser.Roles.First(r => r.Id == 1) != null && AppUser != null)
            {
                ViewBag.Roles = db.Roles.ToList();
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        // POST: Users/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Password,IdRole")] User user, List<int> roles)
        {
            if (roles.Count < 1)
            {
                ModelState.AddModelError("Name", "Pick a role");
            }
            if (ModelState.IsValid && roles.Count > 0)
            {
                var random = new RNGCryptoServiceProvider();
                byte[] salt = new byte[32];
                random.GetNonZeroBytes(salt);
                SaltedPassword pw = PasswordHasher.GenerateSaltedPassword(PasswordHasher.HashPassword(user.Password), salt);
                
                User newUser = new Models.User();
                newUser.Name = user.Name;
                newUser.Password = pw.PasswordHash;
                newUser.Salt = pw.Salt;

                newUser.Roles.Clear();
                foreach (Role role in db.Roles.Where(ro => roles.Contains(ro.Id)))
                {
                    newUser.Roles.Add(role);
                }
                db.Users.Add(newUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }            
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SIS.Lab1_2/Views/Shared/_Layout.cshtml
@using SIS.Lab1_2.Models
@{
    SIS.Lab1_2.Models.User AppUser = Session["UserData"] as SIS.Lab1_2.Models.User;
}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                    @{if (AppUser != null) {
                          if (AppUser.IsInRole("Admin")) { 
                                <li>@Html.ActionLink("Администрирование", "Index", "Users")</li>                                
                            }
                            <li>@Html.ActionLink("Объекты", "Index", "BLObjects")</li>
                        }                        
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>